server:
  port: 8082
  
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/usertransaction?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update  
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  application:
    name: user-transaction-service
  flyway:
    enabled:  true
    baselineOnMigrate: true
    validateOnMigrate: true
    locations: classpath:db/migration
         